### ISSUE TITLE
Transport network inspection

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/planetary-defense#236]
It should be possible to see what commodities flow along links, in which amounts.

Potentially, show flows for selected commodity just as usual with taxture animation. But click/hover and then show numbers would also be good.

* [x] Make commodity identifiers `int` (#269)
* [x] Use arrays where possible (#270)
* [x] Add per-commodity flow to edges (only collapsed network edges? ✔️ #272)
* [x] In the flows view, change commodity visualized on roads (#272)
* [x] ~~(Optional) add some mouse-over information~~
